# Generated by Django 5.1.2 on 2024-10-25 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contextualquestionnaire_last_modified_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='riskassessmentresponse',
            index=models.Index(fields=['questionnaire', 'question'], name='core_riskas_questio_e865a2_idx'),
        ),
    ]
