# Generated by Django 5.1.2 on 2024-10-26 02:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_riskassessmentresponse_core_riskas_questio_e865a2_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manualscore',
            name='score',
            field=models.FloatField(help_text='Score between 0-10', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
    ]
