# Generated by Django 5.1.2 on 2024-10-27 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_manualscore_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
