# Generated by Django 5.1.2 on 2024-10-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_vendorprofile_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskcalculation',
            name='calculation_stages',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='riskcalculation',
            name='factor_scores',
            field=models.JSONField(null=True),
        ),
    ]
